version: '0.1.{build}'

branches:
  only:
    - master

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - nuget restore

build:
  parallel: true
  project: Ionplus.Garuda.sln
  publish_nuget: false

build_script:
  - cmd: dotnet build
  - cmd: dotnet pack

artifacts:
  - path: '**\*.nupkg'
