version: "0.12.{build}"

branches:
  only:
    - master
    - develop
    - /release.*/

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - nuget restore

build_script:
  - cmd: dotnet build /p:TreatWarningsAsErrors=true
  - cmd: dotnet pack

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: Dj4GEf7GNLb/mROmwRhBhYhRemw9o3w98QvI7Ff0sE74euTL4khy5Hfgg3ErZfNg
  skip_symbols: false
  artifact: /.*\.nupkg/

for:
  - branches:
      only:
        - develop

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: "{version}-alpha"
      package_version: "{version}-alpha"
      assembly_version: "{version}-alpha"
      file_version: "{version}-alpha"
      informational_version: "{version}-alpha"

  - branches:
      only:
        - /release.*/

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: "{version}-rc"
      package_version: "{version}-rc"
      assembly_version: "{version}-rc"
      file_version: "{version}-rc"
      informational_version: "{version}-rc"
